name: show_app_ui
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  # UI
  flutter_svg: ^1.1.6
  # modal_bottom_sheet: ^2.1.2
  # pull_to_refresh: ^2.0.0
  gap: ^3.0.0
  # dotted_line: ^3.1.0
  # syncfusion_flutter_sliders: ^21.1.38
  # dotted_border: ^2.0.0+3
  # image_picker: ^0.8.7+2
  # salomon_bottom_bar: ^3.3.2
  # awesome_dialog: ^3.1.0
  google_fonts: ^5.0.0
  # flutter_spinkit: ^5.2.0

  # Animations
  # flutter_bounce: ^1.1.0
  # flutter_animator: ^3.2.2
  # auto_animated: ^3.1.0
  # floating_action_bubble: ^1.1.4
  # loading_animation_widget: ^1.2.0+4

  # Helpers
  flutter_screenutil: ^5.6.1
  # dartz: ^0.10.1
  # meta: ^1.8.0
  # mask_text_input_formatter: ^2.4.0
  # freezed_annotation: ^2.2.0
  # path_provider: ^2.0.12
  path: ^1.8.2
  url_launcher: ^6.1.9
  # get_it: ^7.2.0
  xml: ^6.0.0
  dropdown_search: ^3.0.1
  # flutter_rounded_date_picker: ^3.0.2
  flutter_easyloading: ^3.0.5
  local_auth: ^2.1.6
  fluttertoast: ^8.2.1
  intl: ^0.18.0



  # State management
  # flutter_bloc: ^8.1.2
  # bloc: ^8.1.1
  # bloc_concurrency: ^0.2.1
  provider: ^6.0.5

   # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # cached_network_image: ^3.2.3

    # Networking
  http: ^1.1.0
  dio: ^5.1.1
  # retrofit: ^4.0.1
  # connectivity_plus: ^3.0.3
  requests_inspector: ^2.3.5

  # Models
  equatable: ^2.0.5

  # Localization
  easy_localization: ^3.0.2

   # Navigation
  go_router: ^10.0.0

  html: ^0.15.3
  flutter_spinkit: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/
 

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #     